### ISSUE TITLE
Print current randomSeed

### ISSUE THREAD

**Issue by idontknoweider** [tmhglnd/mercury-playground#33]
I believe that being able to print the current randomSeed could be useful. I personally would like so to be able to explore and be able to save some seeds that were useful, so that later on I can use them again or share them. So that 'cool' randomness is not lost.

**Comment by tmhglnd** [comment]
This is now possible in 2cf53e789f65ee5416f46ce591c94e822a642835 with `getSeed()`. Below is a little example on how you can generate a randomSeed and then print it to see what it was for re-use later.

```js
set scale minor a

// generate a random seed between 1000-10000
set randomSeed random(1 1000 10000)

// print the seed to the console
print getSeed()

list notes random(8 0 12)
new synth saw time(1/16) note(notes 1)
```
